name: Deploy Cloud Function

on:
  workflow_dispatch:

  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
    - name: Deploy Function
      uses: google-github-actions/deploy-cloud-functions@v3
      timeout-minutes: 10
      with:
        name: 'calendarSync'
        runtime: 'gradle'
        region: 'us-central1'
