name: Deploy to Google Cloud
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout sources    
        uses: actions/checkout@v4
    
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      
      - name: Build
        run: ./gradlew build

      - name: Auth Google     
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Deploy
        run: gcloud functions deploy calendarSync --entry-point org.ipuppyp.google.calendar.sync2.function.CalendarSyncFunction --runtime java21 --trigger-http --memory 512MB --update-secrets=/secrets/google-calendar-synch-credentials.json=projects/842556296685/secrets/google-calendar-synch-credentials:latest,/secrets/tokens/StoredCredential=projects/842556296685/secrets/StoredCredential:latest -q
